<a href="https://colab.research.google.com/github/Devendra137/PytorchTut/blob/main/LinearRegPytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')


In [ ]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [ ]:
import torch

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
w = torch.randn(2,3,requires_grad=True)

In [ ]:
b = torch.randn(2,requires_grad=True)

In [ ]:
print(w)

tensor([[-1.5814, -0.9496, -0.6782],
        [ 2.1112,  0.0158,  1.0257]], requires_grad=True)


In [ ]:
print(b)

tensor([ 0.4280, -0.3113], requires_grad=True)


In [ ]:
def model(x):
    return x @ w.t() + b

In [ ]:
finalmod = model(inputs)

In [ ]:
print(finalmod)

tensor([[-207.7943,  198.9709],
        [-270.4415,  258.8443],
        [-303.7269,  244.9746],
        [-226.7953,  253.6605],
        [-247.3170,  218.6793]], grad_fn=<AddBackward0>)


In [ ]:
def mse(t1,t2):
    diff = t1-t2;
    return torch.sum(diff*diff)/diff.numel()

In [ ]:
mseloss = mse(targets,finalmod)
print(mseloss)

tensor(66738.2031, grad_fn=<DivBackward0>)


In [ ]:
mseloss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[-1.5814, -0.9496, -0.6782],
        [ 2.1112,  0.0158,  1.0257]], requires_grad=True)
tensor([[-27512.8789, -29915.0195, -18416.2363],
        [ 12499.5498,  11284.3125,   7427.2607]])


In [ ]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[ 1.1699,  2.0419,  1.1634],
        [ 0.8612, -1.1126,  0.2830]], requires_grad=True)
tensor([ 0.4608, -0.3256], requires_grad=True)


In [ ]:
finalmod = model(inputs)

In [ ]:
mseloss = mse(targets,finalmod)
print(mseloss)

tensor(42193.3320, grad_fn=<DivBackward0>)


In [ ]:

for i in range(100):
    finalmod = model(inputs)
    mseloss = mse(targets,finalmod)
    print("For {} iteration loss is {}".format(i,mseloss))
    print(mseloss)
    mseloss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


For 0 iteration loss is 435.68719482421875
tensor(435.6872, grad_fn=<DivBackward0>)
For 1 iteration loss is 430.2472229003906
tensor(430.2472, grad_fn=<DivBackward0>)
For 2 iteration loss is 424.87579345703125
tensor(424.8758, grad_fn=<DivBackward0>)
For 3 iteration loss is 419.57196044921875
tensor(419.5720, grad_fn=<DivBackward0>)
For 4 iteration loss is 414.3351135253906
tensor(414.3351, grad_fn=<DivBackward0>)
For 5 iteration loss is 409.16424560546875
tensor(409.1642, grad_fn=<DivBackward0>)
For 6 iteration loss is 404.0586853027344
tensor(404.0587, grad_fn=<DivBackward0>)
For 7 iteration loss is 399.0174255371094
tensor(399.0174, grad_fn=<DivBackward0>)
For 8 iteration loss is 394.0396423339844
tensor(394.0396, grad_fn=<DivBackward0>)
For 9 iteration loss is 389.12469482421875
tensor(389.1247, grad_fn=<DivBackward0>)
For 10 iteration loss is 384.271728515625
tensor(384.2717, grad_fn=<DivBackward0>)
For 11 iteration loss is 379.4798278808594
tensor(379.4798, grad_fn=<DivBackward0>

In [ ]:
for i in range(50):
    finalmod = model(inputs)
    mseloss = mse(targets,finalmod)
    print("For {} iteration loss is {}".format(i,mseloss))
    print(mseloss)
    mseloss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()


For 0 iteration loss is 125.43912506103516
tensor(125.4391, grad_fn=<DivBackward0>)
For 1 iteration loss is 123.90733337402344
tensor(123.9073, grad_fn=<DivBackward0>)
For 2 iteration loss is 122.39482116699219
tensor(122.3948, grad_fn=<DivBackward0>)
For 3 iteration loss is 120.9013442993164
tensor(120.9013, grad_fn=<DivBackward0>)
For 4 iteration loss is 119.42658996582031
tensor(119.4266, grad_fn=<DivBackward0>)
For 5 iteration loss is 117.97037506103516
tensor(117.9704, grad_fn=<DivBackward0>)
For 6 iteration loss is 116.53250885009766
tensor(116.5325, grad_fn=<DivBackward0>)
For 7 iteration loss is 115.11271667480469
tensor(115.1127, grad_fn=<DivBackward0>)
For 8 iteration loss is 113.71075439453125
tensor(113.7108, grad_fn=<DivBackward0>)
For 9 iteration loss is 112.32637786865234
tensor(112.3264, grad_fn=<DivBackward0>)
For 10 iteration loss is 110.95948791503906
tensor(110.9595, grad_fn=<DivBackward0>)
For 11 iteration loss is 109.60966491699219
tensor(109.6097, grad_fn=<DivBac

In [ ]:
finalmod = model(inputs)
mseloss = mse(finalmod, targets)
print(mseloss)

tensor(68.3093, grad_fn=<DivBackward0>)
