<a href="https://colab.research.google.com/github/Devendra137/PytorchTut/blob/main/LinRegPytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import numpy as np

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [32]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [35]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [36]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3792,  0.4342,  0.5752],
        [ 0.4869,  0.3363,  0.3079]], requires_grad=True)
Parameter containing:
tensor([-0.4445, -0.3107], requires_grad=True)


In [37]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3792,  0.4342,  0.5752],
         [ 0.4869,  0.3363,  0.3079]], requires_grad=True),
 Parameter containing:
 tensor([-0.4445, -0.3107], requires_grad=True)]

In [42]:
import torch.nn.functional as F
loss_fn = F.mse_loss

In [43]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [44]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [45]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 202.6451
Epoch [20/100], Loss: 167.6659
Epoch [30/100], Loss: 89.7455
Epoch [40/100], Loss: 73.2406
Epoch [50/100], Loss: 35.6946
Epoch [60/100], Loss: 43.0893
Epoch [70/100], Loss: 21.7659
Epoch [80/100], Loss: 24.4334
Epoch [90/100], Loss: 37.2323
Epoch [100/100], Loss: 4.3832
